config/routes.rb
Rails.application.routes.draw do
  get 'upload/image'
  devise_for :users
  resources :posts
  root 'posts#index'
  resources :api_posts, only: [:index, :show]
  resources :images, only: [:create] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api_post.rb
class ApiPost < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    has_many_attached :images
    def url
        helpers = Rails.application.routes.url_helpers
        helpers.rails_representation_url(file.variant({}), only_path: true)
    end
end

app/models/post.rb
class Post < ApplicationRecord
    include Rails.application.routes.url_helpers
    has_one_attached :thumbnail_image
    has_many_attached :images
    def thumbnail_image_url
        # 紐づいている画像のURLを取得する
        thumbnail_image.attached? ? url_for(thumbnail_image).gsub('http:/localhost:3000','https://koddaku-backend.herokuapp.com') : nil
    end
    def url
        helpers = Rails.application.routes.url_helpers
        helpers.rails_representation_url(file.variant({}), only_path: true)
    end
end

app/models/posts_tag.rb
class PostsTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api_posts_controller.rb
class ApiPostsController < ApplicationController
    def index
        @posts = Post.order(created_at: :desc)
        render json: @posts, methods: [:thumbnail_image_url] 
    end
    
    # GET /posts/1 or /posts/1.json
    def show
    @post = Post.find(params[:id])
    render json: @post, methods: [:thumbnail_image_url] 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    def create
        @image = Image.new
        @image_new = Image.new(image_params)
        if @image_new.save
          if Image.count != 0
            @image_new = Image.order(created_at: :desc).first
          end
          @image_tag = '<img src="" width="200">'
          if params["post_id"].present?
            redirect_to edit_post_path(id: params["post_id"], title: params["title"], content: params["content"])
          else
            redirect_to new_post_path(title: params["title"], content: params["content"])
          end
        end
    end

    private
    def title
      params["title"]
    end

    def content
      params["content"]
    end
    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(images:[] )
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
    @image = Image.new
    @image_tag = '<img src="" width="200">'
    if Image.count != 0
      @image_new = Image.order(created_at: :desc).first
    end
    @post_title = params[:title]
    @post_content = params[:content]
  end

  # GET /posts/1/edit
  def edit
    @image = Image.new
    @image_tag = '<img src="" width="200">'
    if Image.count != 0
      @image_new = Image.find(Image.count)
    end
    @post = Post.find(params[:id])
    @post.title = params[:title]
    @post.content = params[:content]
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.publised_on = Time.current

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :thumbnail_image, images:[] )
    end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def image
    file = params[:asset][:file]
    blob = ActiveStorage::Blob.create_after_upload!(
      io: file,
      filename: file.original_filename,
      content_type: file.content_type
    )

    render json: { filename: url_for(blob) }
  end
end

app/helpers/api_posts_helper.rb
module ApiPostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
    def markdown(text)
      unless @markdown
        options = {
          hard_wrap: true
        }
        extensions = {
          no_intra_emphasis: true,
          tables: true,
          fenced_code_blocks: true,
          autolink: true,
          quote: true
        }
        renderer = Redcarpet::Render::HTML.new(options)
        @markdown = Redcarpet::Markdown.new(renderer, extensions)
      end
  
      @markdown.render(text).html_safe
    end
  end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/2.0.1/marked.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/styles/monokai-sublime.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :thumbnail_image %>
    <%= form.text_area :thumbnail_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= form_with model: @post, id: 'form2', local: true do |f| %>
<div class="row">	
<div class = "col-12">
  <div>タイトル</div>
  <%= f.text_field :title,id: 'title',value: @post.title, onkeyup: "inputCheck2()" %>
</div>
<div class = "col-lg-6 col-xs-12　text-area" style="height:820px;">
  <div class="code-block">
    <div>内容</div>
    <%= f.text_area :content,id: 'content',value: @post.content , onkeyup: "inputCheck3()",  style: "min-width: 100%" %>
  </div>
</div>
<div class = "col-lg-6 col-xs-12">
  <div class="code-block">
    <div>表示される内容</div>
    <div id="code_markdown"></div> <%# ここにMarkdownに変換された入力内容が入る %>
  </div>
</div>
<div class = "col-12">
  <div>サムネイル画像</div>
   <%= f.file_field :thumbnail_image %>
</div>
<div class = "col-12">
  <%= f.submit %>
</div>
</div>
<% end %>

<%= form_with model: @image, id: 'form1', local: true do |f| %>
  <div>画像</div>
   <%= f.file_field :images, multiple: true, id: 'file' %><br>
   <%= hidden_field_tag :title, "", {id: 'check2'} %>
   <%= hidden_field_tag :content, "", {id: 'check3'} %>
   <%= hidden_field_tag :post_id, @post.id %>
<% end %>
  <div>画像url生成</div>
  <% if @image_new.present? && @image_new.images.attached? %>
    <% @image_new.images.each do |image| %>
    <%= url_for(image) %>
  <% end %>
  <% end %>
<br>
<%= @image_tag %>
<br>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

<script>

function markdownCode() {
  const codeInput = document.getElementById('content');  // idが'user_answer_code'のもの(textarea)
  const codeMarkdown = document.getElementById('code_markdown');  // idが'code_markdown'のもの(空のdiv)
  if (codeInput == null || codeMarkdown == null) {
    return;  // 該当ページでない場合はアーリーリターン
  }

  codeInput.addEventListener('input', () => {
    const HTML = `${codeInput.value}`;
    codeMarkdown.innerHTML = marked(HTML);
    const pre_code_nodes = document.querySelectorAll("pre code");  // ここがポイント
    for(let i = 0; i < pre_code_nodes.length; ++i){                // ここがポイント
      hljs.highlightBlock(pre_code_nodes[i]);                      // ここがポイント
    }
  });
};
$(document).on('turbolinks:load', function() {　
  alert (aaaa);
  const codeInput = document.getElementById('content');  // idが'content'のもの(textarea)
  const codeMarkdown = document.getElementById('code_markdown');
  const HTML = `${codeInput.value}`;
  codeMarkdown.innerHTML = marked(HTML);
  const pre_code_nodes = document.querySelectorAll("pre code");  // ここがポイント
  for(let i = 0; i < pre_code_nodes.length; ++i){                // ここがポイント
    hljs.highlightBlock(pre_code_nodes[i]);                      // ここがポイント
  }
  markdownCode();
});
window.addEventListener("load", markdownCode);

document.getElementById("file").onchange = function() {
    document.getElementById("form1").submit();
};
function inputCheck3() {
  var inputValue = document.getElementById( "content" ).value;
  document.getElementById( "check3" ).value = inputValue;
}
function inputCheck2() {
  var inputValue = document.getElementById( "title" ).value;
  document.getElementById( "check2" ).value = inputValue;
}
</script>
<style>
textarea { 
   height: 798px;
}
.textarea{
  height: 500px;
}
</style>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>作成日</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.created_at %></td>
        <td><%= link_to 'Show', post,data: {"turbolinks"=>false} %></td>
        <td><%= link_to 'Edit', edit_post_path(post),data: {"turbolinks"=>false} %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, data: {"turbolinks"=>false}%>

app/views/posts/new.html.erb
<%= form_with model: @post, id: 'form2', local: true do |f| %>
<div class="row">	
<div class = "col-12">
  <div>タイトル</div>
  <%= f.text_field :title,id: 'title',value: @post_title, onkeyup: "inputCheck2()" %>
</div>
<div class = "col-lg-6 col-xs-12　text-area" style="height:820px;">
  <div class="code-block">
    <div>内容</div>
    <%= f.text_area :content,id: 'content',value: @post_content , onkeyup: "inputCheck3()",  style: "min-width: 100%" %>
  </div>
</div>
<div class = "col-lg-6 col-xs-12">
  <div class="code-block">
    <div>表示される内容</div>
    <div id="code_markdown"></div> <%# ここにMarkdownに変換された入力内容が入る %>
  </div>
</div>
<div class = "col-12">
  <div>サムネイル画像</div>
   <%= f.file_field :thumbnail_image %>
</div>
<div class = "col-12">
  <%= f.submit %>
</div>
</div>
<% end %>

<%= form_with model: @image, id: 'form1', local: true do |f| %>
  <div>画像</div>
   <%= f.file_field :images, multiple: true, id: 'file' %><br>
   <%= hidden_field_tag :title, "", {id: 'check2'} %>
   <%= hidden_field_tag :content, "", {id: 'check3'} %>
<% end %>
  <div>画像url生成</div>
  <% if @image_new.present? && @image_new.images.attached? %>
    <% @image_new.images.each do |image| %>
    <p>https://koddaku-backend.herokuapp.com<%= url_for(image) %></p>
  <% end %>
  <% end %>
<br>
<%= @image_tag %>
<br>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

<script>

function markdownCode() {
  const codeInput = document.getElementById('content');  // idが'user_answer_code'のもの(textarea)
  const codeMarkdown = document.getElementById('code_markdown');  // idが'code_markdown'のもの(空のdiv)
  if (codeInput == null || codeMarkdown == null) {
    return;  // 該当ページでない場合はアーリーリターン
  }

  codeInput.addEventListener('input', () => {
    const HTML = `${codeInput.value}`;
    codeMarkdown.innerHTML = marked(HTML);
    const pre_code_nodes = document.querySelectorAll("pre code");  // ここがポイント
    for(let i = 0; i < pre_code_nodes.length; ++i){                // ここがポイント
      hljs.highlightBlock(pre_code_nodes[i]);                      // ここがポイント
    }
  });
};
$(document).on('turbolinks:load', function() {　
  alert (aaaa);
  const codeInput = document.getElementById('content');  // idが'content'のもの(textarea)
  const codeMarkdown = document.getElementById('code_markdown');
  const HTML = `${codeInput.value}`;
  codeMarkdown.innerHTML = marked(HTML);
  const pre_code_nodes = document.querySelectorAll("pre code");  // ここがポイント
  for(let i = 0; i < pre_code_nodes.length; ++i){                // ここがポイント
    hljs.highlightBlock(pre_code_nodes[i]);                      // ここがポイント
  }
  markdownCode();
});
window.addEventListener("load", markdownCode);

document.getElementById("file").onchange = function() {
    document.getElementById("form1").submit();
};
function inputCheck3() {
  var inputValue = document.getElementById( "content" ).value;
  document.getElementById( "check3" ).value = inputValue;
}
function inputCheck2() {
  var inputValue = document.getElementById( "title" ).value;
  document.getElementById( "check2" ).value = inputValue;
}
</script>
<style>
textarea { 
   height: 798px;
}
.textarea{
  height: 500px;
}
</style>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class = "row">
<div class = "col-8 offset-2">
  <strong>Title:</strong>
  <%= @post.title %>
</div>
<div class ="col-8 offset-2">
  <strong>Content:</strong>
  <%= markdown(@post.content) %>
</div>
<div class ="col-8 offset-2">
  <strong>Thumbnail image:</strong><br>
  <% if @post.thumbnail_image.attached? %>
    <%= image_tag @post.thumbnail_image, size: '100x100' %>
  <% end %>
</div>
<div class ="col-8 offset-2">
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</div>
</div>

app/views/upload/image.html.erb
<h1>Upload#image</h1>
<p>Find me in app/views/upload/image.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>